language: php
php:
- '7.2'
- '7.3'
-
install:
- cp .env.trav .env
- composer install --no-interaction

before_install:
- openssl aes-256-cbc -K $encrypted_bf2119c2fc05_key -iv $encrypted_bf2119c2fc05_iv
  -in .env.trav.enc -out .env.trav -d

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
