language: php
php:
- '7.2'
- '7.3'
install:
- cp .env.trav .env
- composer install --no-interaction
before_install:
- openssl aes-256-cbc -K $encrypted_bf2119c2fc05_key -iv $encrypted_bf2119c2fc05_iv
  -in .env.trav.enc -out .env.trav -d
script:
- "./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml"
- "./vendor/bin/phpmd src/,tests/ text ./phpmd.xml"
- "./vendor/bin/phpcs src/ --standard=./phpcs.xml"
after_script:
- "./vendor/bin/php-coveralls -v"
- "./vendor/bin/codacycoverage clover ./tests/logs/clover.xml -v"
- https://raw.githubusercontent.com/report-ci/scripts/master/upload.py
- python <(curl -s https://report.ci/upload.py)
